# Generated by Django 5.0.2 on 2024-03-02 08:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('join', '0005_subtask_task_subtasks'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='task',
            name='subtasks',
        ),
        migrations.AddField(
            model_name='task',
            name='subtasks',
            field=models.CharField(default='Test', max_length=500),
        ),
    ]
