# Generated by Django 5.0.2 on 2024-03-02 08:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('join', '0006_remove_task_subtasks_task_subtasks'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='task',
            name='subtasks',
        ),
        migrations.AddField(
            model_name='task',
            name='subtasks',
            field=models.ManyToManyField(related_name='assigned_tasks', to='join.subtask'),
        ),
    ]
