# Generated by Django 5.0.2 on 2024-03-02 10:07

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('join', '0007_remove_task_subtasks_task_subtasks'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='task',
            name='subtasks',
        ),
    ]
