# Generated by Django 5.0.2 on 2024-03-02 10:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('join', '0008_remove_task_subtasks'),
    ]

    operations = [
        migrations.AddField(
            model_name='task',
            name='subtasks',
            field=models.JSONField(default=None),
        ),
    ]
